// Writes protocol/golden/golden_vectors.txt (PROTOCOL.md §10). Run after any protocol change:
//   build\protocol\cpp\Release\redcraft_golden_gen.exe protocol\golden\golden_vectors.txt
#include "golden_values.h"

#include <cstdio>

int main(int argc, char** argv)
{
	if (argc != 2) {
		std::fprintf(stderr, "usage: redcraft_golden_gen <output file>\n");
		return 2;
	}
	FILE* out = nullptr;
	if (fopen_s(&out, argv[1], "wb") != 0 || !out) {
		std::fprintf(stderr, "cannot write %s\n", argv[1]);
		return 1;
	}
	std::fprintf(out,
		"# RedCraft protocol v1.0 golden vectors (docs/PROTOCOL.md section 10).\n"
		"# One complete ring record per line: <NAME> <hex bytes>. Header: typeVersion 1, session 0x11223344, seq 7.\n"
		"# Field values: protocol/cpp/tests/golden_values.cpp and fabric/src/test/java/dev/redcraft/link/GoldenVectorsTest.java.\n"
		"# Generated by redcraft_golden_gen; both test suites compare against this file byte for byte.\n");
	static const char digits[] = "0123456789abcdef";
	for (const auto& v : redcraft::golden::AllVectors()) {
		std::fprintf(out, "%s ", v.name.c_str());
		for (auto b : v.record) {
			std::fputc(digits[b >> 4], out);
			std::fputc(digits[b & 15], out);
		}
		std::fputc('\n', out);
	}
	std::fclose(out);
	std::printf("wrote %s\n", argv[1]);
	return 0;
}
